#! /usr/bin/perl

#W zadanym katalogu przerobić dowiązania twarde do plików w tym katalogu na symboliczne



if ( @ARGV != 1	)
{
	die "Błędna liczba argumentów!";
}

if (! -d $ARGV[0])
{
	die "Plik nie jest katalogiem!";
}

opendir(dir,$ARGV[0]) or die "Nie udało się otworzyć katalogu!";


while($file = readdir(dir))
{
	next unless (-f "$ARGV[0]/$file");;
	$inode = (stat("$ARGV[0]/$file"))[1];
	opendir(dir2,$ARGV[0]);
	while($file2 = readdir(dir2))
	{
		$inode2 = (stat("$ARGV[0]/$file2"))[1];
		if ( "$ARGV[0]/$file" ne "$ARGV[0]/$file2" and $inode == $inode2)
		{
			unlink("$ARGV[0]/$file");
			symlink("$ARGV[0]/$file2","$ARGV[0]/$file");	
		}
	}
	closedir(dir2);	
	
}

closedir(dir);
